services:
  - type: web
    name: cross-clipboard-server
    env: node
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm run start
    envVars:
      - key: CLIPBOARD_PASSWORD
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: CLIPBOARD_STORE_PATH
        value: /opt/render/project/server/data/clipboard.json
